### ISSUE TITLE
TAC Website - Add New Member and Update Contents

### ISSUE THREAD

**Issue by tgorkin** [ucfoundation/foundation#1]
The TAC website page (https://uc.foundation/tac/) needs to be updated to reflect the two new members:

- Prem Ramaswami, Head of Product, Sidewalk Labs, Inc.
- Javier De la Torre, Founder and CSO at CARTO

There was also a suggestion to update all members entries on this page with the following (similar to https://www.cncf.io/people/technical-oversight-committee/):
- Headshots
- Brief bios
- Twitter, LinkedIn, Github profile links

**Comment by danlopez00** [comment]
moving profiles/headshots to new ticket
